# Generated by Django 5.1.5 on 2025-02-22 00:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('password', models.CharField(max_length=256, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Пароль')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Пошта')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='Номер телефону')),
                ('login', models.CharField(max_length=100, verbose_name='Логін')),
                ('password', models.CharField(max_length=256, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Пароль')),
            ],
        ),
    ]
