# Generated by Django 5.1.4 on 2025-02-11 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_delete_item_remove_category_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
