# Generated by Django 5.1.4 on 2025-02-20 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_productadmin_product_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='cover_type',
            field=models.CharField(default='DefaultCoverType', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='format',
            field=models.CharField(default='DefaultFormat', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='illustrations',
            field=models.CharField(default='DefaultIllustrations', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='isbn',
            field=models.CharField(default='0000', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='language',
            field=models.CharField(default='English', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='pages',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.PositiveIntegerField(default=500, help_text='Вага (в грамах)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='year_published',
            field=models.PositiveIntegerField(default=2020),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='publisher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.publisher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='products', to='store.section'),
        ),
    ]
