# Generated by Django 5.1.5 on 2025-02-22 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_publisher_section_product_author_product_cover_type_and_more'),
    ]

    operations = [
    ]
