# Generated by Django 5.1.5 on 2025-02-22 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20250222_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover_type',
            field=models.CharField(default='DefaultCoverType', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='format',
            field=models.CharField(default='DefaultFormat', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='illustrations',
            field=models.CharField(default='DefaultIllustrations', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='isbn',
            field=models.CharField(default='0000', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='language',
            field=models.CharField(default='English', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='pages',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.PositiveIntegerField(default=500, help_text='Вага (в грамах)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='year_published',
            field=models.PositiveIntegerField(default=2020),
        ),
    ]
